data-sources:
  postgres:
    host: localhost
    port: 3306
    username: root
    password: password
    database: database
    options:
      connectionTimeout: "15"
      leakDetectionThreshold: "60"
      maximumPoolSize: "20"
      cachePrepStmts: "true"
      prepStmtCacheSize: "250"
      prepStmtCacheSqlLimit: "2048"
      zeroDateTimeBehavior: "convertToNull"
  redis:
    host: localhost
    port: 6379
    password: ''
    options:
      maxWaitTime: "15"
      maxTotalTime: "125"
      maxIdleTime: "125"
      minIdleTime: "16"